import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "RentNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased")}>
      <body className="min-h-full flex flex-col">
        {/* <header>
          <Navbar></Navbar>
        </header> */}
        {children}
      </body>
    </html>
  );
}
